compiler: D:\Steam\steamapps\common\Skyrim\Papyrus Compiler\PapyrusCompiler.exe
flags: TESV_Papyrus_Flags.flg
output: D:\Steam\steamapps\common\Skyrim\Data\Scripts
imports:
    - D:\Users\Infernio\Desktop\Programming\Wildfire\scripts\source
    - D:\Steam\steamapps\common\Skyrim\Data\Scripts\Source
    - D:\Steam\steamapps\common\Skyrim\Data\Scripts
